# Generated by Django 5.2.7 on 2025-10-27 04:18

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page", "verbose_name_plural": "Home Pages"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_description",
            field=models.TextField(
                blank=True, help_text="Description for the about section"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_title",
            field=models.CharField(
                blank=True, help_text="Title for the about section", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_subtitle",
            field=models.CharField(
                blank=True, help_text="Subtitle for the homepage banner", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_title",
            field=models.CharField(
                blank=True,
                help_text="SEO-friendly title for the homepage",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("hero_banner", 22),
                    ("features", 27),
                    ("testimonials", 34),
                    ("stats", 40),
                    ("cta_section", 47),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "Center Aligned"),
                                ("left", "Left Aligned"),
                                ("right", "Right Aligned"),
                                ("full", "Full Width"),
                                ("split", "Split Layout"),
                                ("overlap", "Content Overlap"),
                            ],
                            "help_text": "Select the layout style for the hero banner.",
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("image", "Image"),
                                ("video", "Video"),
                                ("color", "Solid Color"),
                                ("gradient", "Gradient"),
                            ],
                            "help_text": "Select the background type.",
                        },
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Background image for the hero banner.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Background color in hex format (e.g., #FF0000).",
                            "max_length": 7,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Background video URL (YouTube or Vimeo).",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main headline for the hero banner.",
                            "max_length": 150,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Subtitle for the hero banner.",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Detailed description for the hero banner.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Primary CTA text.",
                            "max_length": 150,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Primary CTA link.", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                                ("ghost", "Ghost"),
                            ],
                            "help_text": "Primary CTA style.",
                        },
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Secondary CTA text.",
                            "max_length": 150,
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Secondary CTA link.", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                                ("ghost", "Ghost"),
                            ],
                            "help_text": "Secondary CTA style.",
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("0", "0%"),
                                ("25", "25%"),
                                ("50", "50%"),
                                ("75", "75%"),
                                ("90", "90%"),
                            ],
                            "help_text": "Overlay opacity for better readability.",
                        },
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ],
                            "help_text": "Text alignment within the hero banner.",
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("none", "None"),
                                ("fade-in", "Fade In"),
                                ("fade-in-up", "Fade In Up"),
                                ("fade-in-down", "Fade In Down"),
                                ("fade-in-left", "Fade In Left"),
                                ("fade-in-right", "Fade In Right"),
                                ("zoom-in", "Zoom In"),
                                ("zoom-in-up", "Zoom In Up"),
                                ("zoom-in-down", "Zoom In Down"),
                                ("slide-in-up", "Slide In Up"),
                                ("slide-in-down", "Slide In Down"),
                                ("slide-in-left", "Slide In Left"),
                                ("slide-in-right", "Slide In Right"),
                            ],
                            "help_text": "Choose the animation for the hero content.",
                        },
                    ),
                    17: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Enable parallax effect for background.",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Enable particle background effect.",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("narrow", "Narrow (600px)"),
                                ("medium", "Medium (900px)"),
                                ("wide", "Wide (1200px)"),
                                ("full", "Full Width"),
                            ],
                            "help_text": "Content container width.",
                        },
                    ),
                    20: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Top padding in pixels.",
                            "max_value": 200,
                            "min_value": 0,
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Bottom padding in pixels.",
                            "max_value": 200,
                            "min_value": 0,
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("layout_style", 0),
                                ("background_type", 1),
                                ("background_image", 2),
                                ("background_color", 3),
                                ("background_video", 4),
                                ("headline", 5),
                                ("subtitle", 6),
                                ("description", 7),
                                ("cta_primary", 8),
                                ("cta_primary_link", 9),
                                ("cta_primary_style", 10),
                                ("cta_secondary", 11),
                                ("cta_secondary_link", 12),
                                ("cta_secondary_style", 13),
                                ("overlay_opacity", 14),
                                ("text_alignment", 15),
                                ("animation_style", 16),
                                ("enable_parallax", 17),
                                ("enable_particles", 18),
                                ("content_width", 19),
                                ("padding_top", 20),
                                ("padding_bottom", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Icon for the feature.", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Feature title.",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    25: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Feature description.",
                            "max_length": 300,
                            "required": True,
                        },
                    ),
                    26: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Optional link for the feature.",
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 23),
                                ("title", 24),
                                ("description", 25),
                                ("link", 26),
                            ]
                        ],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Customer testimonial.",
                            "max_length": 500,
                            "required": True,
                        },
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Customer name.",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Customer role or position.",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Customer company.",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Customer avatar or photo.", "required": False},
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("5", "5 Stars"),
                                ("4", "4 Stars"),
                                ("3", "3 Stars"),
                                ("2", "2 Stars"),
                                ("1", "1 Star"),
                            ],
                            "help_text": "Customer rating.",
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 28),
                                ("author", 29),
                                ("role", 30),
                                ("company", 31),
                                ("avatar", 32),
                                ("rating", 33),
                            ]
                        ],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Statistical value (e.g., "1000+", "99%").',
                            "max_length": 20,
                            "required": True,
                        },
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Stat label (e.g., "Customers", "Satisfaction").',
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    37: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional description.",
                            "max_length": 150,
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 35), ("label", 36), ("description", 37)]],
                        {},
                    ),
                    39: (
                        "wagtail.blocks.ListBlock",
                        (38,),
                        {
                            "help_text": "Add statistics to display.",
                            "max_num": 6,
                            "min_num": 1,
                        },
                    ),
                    40: ("wagtail.blocks.StructBlock", [[("stat", 39)]], {}),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Section title.",
                            "max_length": 150,
                            "required": True,
                        },
                    ),
                    42: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Section description.",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "CTA button text.",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    44: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "CTA button link.", "required": True},
                    ),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                            ],
                            "help_text": "Button style.",
                        },
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Background color in hex format.",
                            "max_length": 7,
                            "required": False,
                        },
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 41),
                                ("description", 42),
                                ("button_text", 43),
                                ("button_link", 44),
                                ("button_style", 45),
                                ("background_color", 46),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
