# Generated by Django 5.0.14 on 2025-10-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_homepage_options_alter_homepage_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThemeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this theme configuration",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Make this the active theme for the site",
                    ),
                ),
                (
                    "theme_mode",
                    models.CharField(
                        choices=[
                            ("system", "System Default"),
                            ("light", "Light Theme"),
                            ("dark", "Dark Theme"),
                            ("blue", "Ocean Breeze"),
                            ("green", "Forest Green"),
                            ("contrast", "High Contrast"),
                            ("sunset", "Sunset Glow"),
                            ("custom", "Custom Theme"),
                        ],
                        default="system",
                        help_text="Select the theme mode for the website.",
                        max_length=20,
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        blank=True,
                        help_text="Primary accent color in hex format (e.g., #3B82F6).",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        blank=True,
                        help_text="Secondary color in hex format (e.g., #10B981).",
                        max_length=7,
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        blank=True,
                        help_text="Main background color in hex format (e.g., #FFFFFF).",
                        max_length=7,
                    ),
                ),
                (
                    "surface_color",
                    models.CharField(
                        blank=True,
                        help_text="Surface elements color in hex format (e.g., cards, panels).",
                        max_length=7,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        blank=True,
                        help_text="Primary text color in hex format (e.g., #1E293B).",
                        max_length=7,
                    ),
                ),
                (
                    "text_secondary_color",
                    models.CharField(
                        blank=True,
                        help_text="Secondary text color in hex format (e.g., #64748B).",
                        max_length=7,
                    ),
                ),
                (
                    "border_color",
                    models.CharField(
                        blank=True,
                        help_text="Border and divider color in hex format (e.g., #E2E8F0).",
                        max_length=7,
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        choices=[
                            ("system", "System Default"),
                            ("sans-serif", "Sans Serif"),
                            ("serif", "Serif"),
                            ("monospace", "Monospace"),
                        ],
                        default="system",
                        help_text="Select the font family for the website.",
                        max_length=20,
                    ),
                ),
                (
                    "font_size_scale",
                    models.CharField(
                        choices=[
                            ("sm", "Small"),
                            ("md", "Medium"),
                            ("lg", "Large"),
                            ("xl", "Extra Large"),
                        ],
                        default="md",
                        help_text="Adjust the overall font size scale.",
                        max_length=10,
                    ),
                ),
                (
                    "switcher_position",
                    models.CharField(
                        choices=[
                            ("top-left", "Top Left"),
                            ("top-right", "Top Right"),
                            ("bottom-left", "Bottom Left"),
                            ("bottom-right", "Bottom Right"),
                        ],
                        default="bottom-right",
                        help_text="Position of the theme switcher widget.",
                        max_length=20,
                    ),
                ),
                (
                    "switcher_style",
                    models.CharField(
                        choices=[
                            ("compact", "Compact"),
                            ("full", "Full"),
                            ("expanded", "Expanded"),
                        ],
                        default="full",
                        help_text="Visual style of the theme switcher widget.",
                        max_length=20,
                    ),
                ),
                (
                    "enable_transitions",
                    models.BooleanField(
                        default=True,
                        help_text="Enable smooth transitions between theme changes.",
                    ),
                ),
                (
                    "transition_duration",
                    models.CharField(
                        choices=[
                            ("fast", "Fast"),
                            ("normal", "Normal"),
                            ("slow", "Slow"),
                        ],
                        default="normal",
                        help_text="Duration of theme transition animations.",
                        max_length=10,
                    ),
                ),
                (
                    "enable_persistence",
                    models.BooleanField(
                        default=True,
                        help_text="Save user theme preference across sessions.",
                    ),
                ),
                (
                    "enable_auto_detect",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically detect system theme changes.",
                    ),
                ),
                (
                    "auto_contrast_adjustment",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically adjust text colors for better contrast.",
                    ),
                ),
                (
                    "enable_high_contrast_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Enable high contrast mode for improved accessibility.",
                    ),
                ),
                (
                    "focus_outline_style",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("thick", "Thick"),
                            ("colorful", "Colorful"),
                        ],
                        default="default",
                        help_text="Style of focus outlines for keyboard navigation.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Theme Setting",
                "verbose_name_plural": "Theme Settings",
            },
        ),
    ]
