# Generated by Django 5.0.14 on 2025-10-27 07:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_homepage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("hero_banner", 22),
                    ("hero_carousel", 42),
                    ("hero_video_background", 57),
                    ("features", 62),
                    ("testimonials", 69),
                    ("stats", 75),
                    ("cta_section", 82),
                    ("theme_selector", 105),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("center", "Center Aligned"),
                                ("left", "Left Aligned"),
                                ("right", "Right Aligned"),
                                ("full", "Full Width"),
                                ("split", "Split Layout"),
                                ("overlap", "Content Overlap"),
                            ],
                            "help_text": "Select the layout style for the hero banner.",
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("image", "Image"),
                                ("video", "Video"),
                                ("color", "Solid Color"),
                                ("gradient", "Gradient"),
                            ],
                            "help_text": "Select the background type.",
                        },
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Background image for the hero banner.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Background color in hex format (e.g., #FF0000).",
                            "max_length": 7,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Background video URL (YouTube or Vimeo).",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main headline for the hero banner.",
                            "max_length": 150,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Subtitle for the hero banner.",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Detailed description for the hero banner.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Primary CTA text.",
                            "max_length": 150,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Primary CTA link.", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                                ("ghost", "Ghost"),
                            ],
                            "help_text": "Primary CTA style.",
                        },
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Secondary CTA text.",
                            "max_length": 150,
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Secondary CTA link.", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                                ("ghost", "Ghost"),
                            ],
                            "help_text": "Secondary CTA style.",
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("0", "0%"),
                                ("25", "25%"),
                                ("50", "50%"),
                                ("75", "75%"),
                                ("90", "90%"),
                            ],
                            "help_text": "Overlay opacity for better readability.",
                        },
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ],
                            "help_text": "Text alignment within the hero banner.",
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("none", "None"),
                                ("fade-in", "Fade In"),
                                ("fade-in-up", "Fade In Up"),
                                ("fade-in-down", "Fade In Down"),
                                ("fade-in-left", "Fade In Left"),
                                ("fade-in-right", "Fade In Right"),
                                ("zoom-in", "Zoom In"),
                                ("zoom-in-up", "Zoom In Up"),
                                ("zoom-in-down", "Zoom In Down"),
                                ("slide-in-up", "Slide In Up"),
                                ("slide-in-down", "Slide In Down"),
                                ("slide-in-left", "Slide In Left"),
                                ("slide-in-right", "Slide In Right"),
                            ],
                            "help_text": "Choose the animation for the hero content.",
                        },
                    ),
                    17: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Enable parallax effect for background.",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Enable particle background effect.",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("narrow", "Narrow (600px)"),
                                ("medium", "Medium (900px)"),
                                ("wide", "Wide (1200px)"),
                                ("full", "Full Width"),
                            ],
                            "help_text": "Content container width.",
                        },
                    ),
                    20: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Top padding in pixels.",
                            "max_value": 200,
                            "min_value": 0,
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Bottom padding in pixels.",
                            "max_value": 200,
                            "min_value": 0,
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("layout_style", 0),
                                ("background_type", 1),
                                ("background_image", 2),
                                ("background_color", 3),
                                ("background_video", 4),
                                ("headline", 5),
                                ("subtitle", 6),
                                ("description", 7),
                                ("cta_primary", 8),
                                ("cta_primary_link", 9),
                                ("cta_primary_style", 10),
                                ("cta_secondary", 11),
                                ("cta_secondary_link", 12),
                                ("cta_secondary_style", 13),
                                ("overlay_opacity", 14),
                                ("text_alignment", 15),
                                ("animation_style", 16),
                                ("enable_parallax", 17),
                                ("enable_particles", 18),
                                ("content_width", 19),
                                ("padding_top", 20),
                                ("padding_bottom", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Automatically rotate slides every few seconds.",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("3000", "3 seconds"),
                                ("5000", "5 seconds"),
                                ("7000", "7 seconds"),
                                ("10000", "10 seconds"),
                            ],
                            "help_text": "Time between slide transitions.",
                        },
                    ),
                    25: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show slide position indicators.",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show previous/next navigation arrows.",
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Pause rotation when user hovers over carousel.",
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "URL for AJAX requests. Leave blank to disable AJAX functionality.",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("GET", "GET"), ("POST", "POST")],
                            "help_text": "HTTP method for AJAX requests.",
                        },
                    ),
                    30: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Background image for this slide.",
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main headline for this slide.",
                            "max_length": 150,
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Subtitle for this slide.",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Detailed description for this slide.",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "CTA button text.",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    35: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "CTA button link.", "required": False},
                    ),
                    36: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                                ("ghost", "Ghost"),
                            ],
                            "help_text": "CTA button style.",
                        },
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 30),
                                ("background_color", 3),
                                ("headline", 31),
                                ("subtitle", 32),
                                ("description", 33),
                                ("cta_text", 34),
                                ("cta_link", 35),
                                ("cta_style", 36),
                            ]
                        ],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.ListBlock",
                        (37,),
                        {
                            "help_text": "Add slides to the carousel (1-5 slides recommended).",
                            "max_num": 5,
                            "min_num": 1,
                        },
                    ),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ],
                            "help_text": "Text alignment within slides.",
                        },
                    ),
                    40: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fade", "Fade"),
                                ("slide", "Slide"),
                                ("zoom", "Zoom"),
                            ],
                            "help_text": "Transition animation style.",
                        },
                    ),
                    41: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Enable parallax effect for background images.",
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("auto_rotate", 23),
                                ("rotation_speed", 24),
                                ("show_indicators", 25),
                                ("show_navigation", 26),
                                ("pause_on_hover", 27),
                                ("ajax_url", 28),
                                ("ajax_method", 29),
                                ("slides", 38),
                                ("overlay_opacity", 14),
                                ("text_alignment", 39),
                                ("animation_style", 40),
                                ("enable_parallax", 41),
                                ("content_width", 19),
                                ("padding_top", 20),
                                ("padding_bottom", 21),
                            ]
                        ],
                        {},
                    ),
                    43: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "URL to the background video (MP4 format recommended).",
                            "required": True,
                        },
                    ),
                    44: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Fallback image for mobile devices or when video is disabled.",
                            "required": True,
                        },
                    ),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("none", "None"),
                                ("dark", "Dark Gradient"),
                                ("light", "Light Gradient"),
                                ("blue", "Blue Gradient"),
                                ("green", "Green Gradient"),
                                ("purple", "Purple Gradient"),
                            ],
                            "help_text": "Gradient overlay for better text readability.",
                        },
                    ),
                    46: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("0", "0%"),
                                ("10", "10%"),
                                ("25", "25%"),
                                ("50", "50%"),
                                ("75", "75%"),
                                ("90", "90%"),
                            ],
                            "help_text": "Overlay opacity for better readability.",
                        },
                    ),
                    47: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main headline for the hero section.",
                            "max_length": 150,
                            "required": True,
                        },
                    ),
                    48: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Subtitle for the hero section.",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    49: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Detailed description for the hero section.",
                            "required": False,
                        },
                    ),
                    50: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ],
                            "help_text": "Content alignment within the hero section.",
                        },
                    ),
                    51: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("top", "Top"),
                                ("middle", "Middle"),
                                ("bottom", "Bottom"),
                            ],
                            "help_text": "Vertical position of content within the hero section.",
                        },
                    ),
                    52: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Mute the video by default (recommended for autoplay).",
                            "required": False,
                        },
                    ),
                    53: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Loop the video continuously.",
                            "required": False,
                        },
                    ),
                    54: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Autoplay the video when page loads.",
                            "required": False,
                        },
                    ),
                    55: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Disable video on mobile devices to save bandwidth.",
                            "required": False,
                        },
                    ),
                    56: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("none", "None"),
                                ("fade-in", "Fade In"),
                                ("fade-in-up", "Fade In Up"),
                                ("fade-in-down", "Fade In Down"),
                                ("slide-in-up", "Slide In Up"),
                                ("slide-in-down", "Slide In Down"),
                            ],
                            "help_text": "Animation for the content.",
                        },
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_video", 43),
                                ("fallback_image", 44),
                                ("overlay_gradient", 45),
                                ("overlay_opacity", 46),
                                ("headline", 47),
                                ("subtitle", 48),
                                ("description", 49),
                                ("cta_primary", 8),
                                ("cta_primary_link", 9),
                                ("cta_primary_style", 10),
                                ("cta_secondary", 11),
                                ("cta_secondary_link", 12),
                                ("cta_secondary_style", 13),
                                ("content_alignment", 50),
                                ("content_vertical_position", 51),
                                ("content_width", 19),
                                ("enable_mute", 52),
                                ("enable_loop", 53),
                                ("enable_autoplay", 54),
                                ("disable_on_mobile", 55),
                                ("animation_style", 56),
                            ]
                        ],
                        {},
                    ),
                    58: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Icon for the feature.", "required": False},
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Feature title.",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    60: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Feature description.",
                            "max_length": 300,
                            "required": True,
                        },
                    ),
                    61: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Optional link for the feature.",
                            "required": False,
                        },
                    ),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 58),
                                ("title", 59),
                                ("description", 60),
                                ("link", 61),
                            ]
                        ],
                        {},
                    ),
                    63: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Customer testimonial.",
                            "max_length": 500,
                            "required": True,
                        },
                    ),
                    64: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Customer name.",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    65: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Customer role or position.",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Customer company.",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    67: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Customer avatar or photo.", "required": False},
                    ),
                    68: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("5", "5 Stars"),
                                ("4", "4 Stars"),
                                ("3", "3 Stars"),
                                ("2", "2 Stars"),
                                ("1", "1 Star"),
                            ],
                            "help_text": "Customer rating.",
                        },
                    ),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 63),
                                ("author", 64),
                                ("role", 65),
                                ("company", 66),
                                ("avatar", 67),
                                ("rating", 68),
                            ]
                        ],
                        {},
                    ),
                    70: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Statistical value (e.g., "1000+", "99%").',
                            "max_length": 20,
                            "required": True,
                        },
                    ),
                    71: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Stat label (e.g., "Customers", "Satisfaction").',
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    72: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional description.",
                            "max_length": 150,
                            "required": False,
                        },
                    ),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 70), ("label", 71), ("description", 72)]],
                        {},
                    ),
                    74: (
                        "wagtail.blocks.ListBlock",
                        (73,),
                        {
                            "help_text": "Add statistics to display.",
                            "max_num": 6,
                            "min_num": 1,
                        },
                    ),
                    75: ("wagtail.blocks.StructBlock", [[("stat", 74)]], {}),
                    76: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Section title.",
                            "max_length": 150,
                            "required": True,
                        },
                    ),
                    77: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Section description.",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    78: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "CTA button text.",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    79: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "CTA button link.", "required": True},
                    ),
                    80: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                            ],
                            "help_text": "Button style.",
                        },
                    ),
                    81: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Background color in hex format.",
                            "max_length": 7,
                            "required": False,
                        },
                    ),
                    82: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 76),
                                ("description", 77),
                                ("button_text", 78),
                                ("button_link", 79),
                                ("button_style", 80),
                                ("background_color", 81),
                            ]
                        ],
                        {},
                    ),
                    83: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("system", "System Default"),
                                ("light", "Light Theme"),
                                ("dark", "Dark Theme"),
                                ("blue", "Ocean Breeze"),
                                ("green", "Forest Green"),
                                ("contrast", "High Contrast"),
                                ("sunset", "Sunset Glow"),
                                ("custom", "Custom Theme"),
                            ],
                            "help_text": 'Select the theme mode for the website. "System Default" follows the user\'s OS preference.',
                        },
                    ),
                    84: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": 'Enable advanced theme customization options. Only applies to "Custom Theme" mode.',
                            "required": False,
                        },
                    ),
                    85: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Primary accent color in hex format (e.g., #3B82F6). Used for buttons, links, and highlights.",
                            "max_length": 7,
                            "required": False,
                        },
                    ),
                    86: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Secondary color in hex format (e.g., #10B981). Used for secondary elements and accents.",
                            "max_length": 7,
                            "required": False,
                        },
                    ),
                    87: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main background color in hex format (e.g., #FFFFFF).",
                            "max_length": 7,
                            "required": False,
                        },
                    ),
                    88: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Surface elements color in hex format (e.g., cards, panels).",
                            "max_length": 7,
                            "required": False,
                        },
                    ),
                    89: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Primary text color in hex format (e.g., #1E293B).",
                            "max_length": 7,
                            "required": False,
                        },
                    ),
                    90: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Secondary text color in hex format (e.g., #64748B).",
                            "max_length": 7,
                            "required": False,
                        },
                    ),
                    91: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Border and divider color in hex format (e.g., #E2E8F0).",
                            "max_length": 7,
                            "required": False,
                        },
                    ),
                    92: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("system", "System Default"),
                                ("sans-serif", "Sans Serif (Inter, Roboto, etc.)"),
                                ("serif", "Serif (Merriweather, Georgia, etc.)"),
                                ("monospace", "Monospace (Fira Code, Consolas, etc.)"),
                            ],
                            "help_text": "Select the font family for the website.",
                        },
                    ),
                    93: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small (14px base)"),
                                ("md", "Medium (16px base)"),
                                ("lg", "Large (18px base)"),
                                ("xl", "Extra Large (20px base)"),
                            ],
                            "help_text": "Adjust the overall font size scale for better readability.",
                        },
                    ),
                    94: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show the theme switcher widget on the page for user theme selection.",
                            "required": False,
                        },
                    ),
                    95: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("top-left", "Top Left"),
                                ("top-right", "Top Right"),
                                ("bottom-left", "Bottom Left"),
                                ("bottom-right", "Bottom Right"),
                            ],
                            "help_text": "Position of the theme switcher widget on the page.",
                        },
                    ),
                    96: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("compact", "Compact (Icon Only)"),
                                ("full", "Full (Icon + Text)"),
                                ("expanded", "Expanded (Full Options)"),
                            ],
                            "help_text": "Visual style of the theme switcher widget.",
                        },
                    ),
                    97: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable smooth transitions between theme changes.",
                            "required": False,
                        },
                    ),
                    98: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fast", "Fast (150ms)"),
                                ("normal", "Normal (300ms)"),
                                ("slow", "Slow (500ms)"),
                            ],
                            "help_text": "Duration of theme transition animations.",
                        },
                    ),
                    99: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Save user theme preference across browser sessions using localStorage.",
                            "required": False,
                        },
                    ),
                    100: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Save user theme preference on the server (requires user authentication).",
                            "required": False,
                        },
                    ),
                    101: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Automatically detect and adapt to system theme changes.",
                            "required": False,
                        },
                    ),
                    102: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Automatically adjust text colors for better contrast on custom backgrounds.",
                            "required": False,
                        },
                    ),
                    103: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Enable high contrast mode for improved accessibility.",
                            "required": False,
                        },
                    ),
                    104: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default Browser Outline"),
                                ("thick", "Thick Visible Outline"),
                                ("colorful", "Colorful Enhanced Outline"),
                            ],
                            "help_text": "Style of focus outlines for keyboard navigation.",
                        },
                    ),
                    105: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("theme_mode", 83),
                                ("enable_customization", 84),
                                ("primary_color", 85),
                                ("secondary_color", 86),
                                ("background_color", 87),
                                ("surface_color", 88),
                                ("text_color", 89),
                                ("text_secondary_color", 90),
                                ("border_color", 91),
                                ("font_family", 92),
                                ("font_size_scale", 93),
                                ("show_theme_switcher", 94),
                                ("switcher_position", 95),
                                ("switcher_style", 96),
                                ("enable_transitions", 97),
                                ("transition_duration", 98),
                                ("enable_persistence", 99),
                                ("enable_server_persistence", 100),
                                ("enable_auto_detect", 101),
                                ("auto_contrast_adjustment", 102),
                                ("enable_high_contrast_mode", 103),
                                ("focus_outline_style", 104),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
