# Generated by Django 5.0.14 on 2025-10-27 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_homepage_content"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarouselSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this carousel configuration",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Make this the active carousel configuration",
                    ),
                ),
                (
                    "auto_rotate",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically rotate slides every few seconds.",
                    ),
                ),
                (
                    "rotation_speed",
                    models.IntegerField(
                        choices=[
                            (3000, "3 seconds"),
                            (5000, "5 seconds"),
                            (7000, "7 seconds"),
                            (10000, "10 seconds"),
                        ],
                        default=5000,
                        help_text="Time between slide transitions.",
                    ),
                ),
                (
                    "show_indicators",
                    models.BooleanField(
                        default=True, help_text="Show slide position indicators."
                    ),
                ),
                (
                    "show_navigation",
                    models.BooleanField(
                        default=True, help_text="Show previous/next navigation arrows."
                    ),
                ),
                (
                    "pause_on_hover",
                    models.BooleanField(
                        default=True,
                        help_text="Pause rotation when user hovers over carousel.",
                    ),
                ),
                (
                    "ajax_url",
                    models.URLField(
                        blank=True,
                        help_text="URL for AJAX requests. Leave blank to disable AJAX functionality.",
                        null=True,
                    ),
                ),
                (
                    "ajax_method",
                    models.CharField(
                        choices=[("GET", "GET"), ("POST", "POST")],
                        default="POST",
                        help_text="HTTP method for AJAX requests.",
                        max_length=10,
                    ),
                ),
                (
                    "overlay_opacity",
                    models.CharField(
                        choices=[
                            ("0", "0%"),
                            ("25", "25%"),
                            ("50", "50%"),
                            ("75", "75%"),
                            ("90", "90%"),
                        ],
                        default="50",
                        help_text="Overlay opacity for better readability.",
                        max_length=10,
                    ),
                ),
                (
                    "text_alignment",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                        ],
                        default="center",
                        help_text="Text alignment within slides.",
                        max_length=10,
                    ),
                ),
                (
                    "animation_style",
                    models.CharField(
                        choices=[
                            ("fade", "Fade"),
                            ("slide", "Slide"),
                            ("zoom", "Zoom"),
                        ],
                        default="fade",
                        help_text="Transition animation style.",
                        max_length=20,
                    ),
                ),
                (
                    "content_width",
                    models.CharField(
                        choices=[
                            ("narrow", "Narrow (600px)"),
                            ("medium", "Medium (900px)"),
                            ("wide", "Wide (1200px)"),
                            ("full", "Full Width"),
                        ],
                        default="medium",
                        help_text="Content container width.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Carousel Setting",
                "verbose_name_plural": "Carousel Settings",
            },
        ),
        migrations.CreateModel(
            name="VideoBackgroundSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this video background configuration",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Make this the active video background configuration",
                    ),
                ),
                (
                    "background_video",
                    models.URLField(
                        help_text="URL to the background video (MP4 format recommended)."
                    ),
                ),
                (
                    "overlay_gradient",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("dark", "Dark Gradient"),
                            ("light", "Light Gradient"),
                            ("blue", "Blue Gradient"),
                            ("green", "Green Gradient"),
                            ("purple", "Purple Gradient"),
                        ],
                        default="dark",
                        help_text="Gradient overlay for better text readability.",
                        max_length=20,
                    ),
                ),
                (
                    "overlay_opacity",
                    models.CharField(
                        choices=[
                            ("0", "0%"),
                            ("10", "10%"),
                            ("25", "25%"),
                            ("50", "50%"),
                            ("75", "75%"),
                            ("90", "90%"),
                        ],
                        default="50",
                        help_text="Overlay opacity for better readability.",
                        max_length=10,
                    ),
                ),
                (
                    "content_alignment",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                        ],
                        default="center",
                        help_text="Content alignment within the hero section.",
                        max_length=10,
                    ),
                ),
                (
                    "content_vertical_position",
                    models.CharField(
                        choices=[
                            ("top", "Top"),
                            ("middle", "Middle"),
                            ("bottom", "Bottom"),
                        ],
                        default="middle",
                        help_text="Vertical position of content within the hero section.",
                        max_length=10,
                    ),
                ),
                (
                    "content_width",
                    models.CharField(
                        choices=[
                            ("narrow", "Narrow (600px)"),
                            ("medium", "Medium (900px)"),
                            ("wide", "Wide (1200px)"),
                            ("full", "Full Width"),
                        ],
                        default="medium",
                        help_text="Content container width.",
                        max_length=20,
                    ),
                ),
                (
                    "enable_mute",
                    models.BooleanField(
                        default=True,
                        help_text="Mute the video by default (recommended for autoplay).",
                    ),
                ),
                (
                    "enable_loop",
                    models.BooleanField(
                        default=True, help_text="Loop the video continuously."
                    ),
                ),
                (
                    "enable_autoplay",
                    models.BooleanField(
                        default=True, help_text="Autoplay the video when page loads."
                    ),
                ),
                (
                    "disable_on_mobile",
                    models.BooleanField(
                        default=False,
                        help_text="Disable video on mobile devices to save bandwidth.",
                    ),
                ),
                (
                    "animation_style",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("fade-in", "Fade In"),
                            ("fade-in-up", "Fade In Up"),
                            ("fade-in-down", "Fade In Down"),
                            ("slide-in-up", "Slide In Up"),
                            ("slide-in-down", "Slide In Down"),
                        ],
                        default="fade-in",
                        help_text="Animation for the content.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fallback_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fallback image for mobile devices or when video is disabled.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Background Setting",
                "verbose_name_plural": "Video Background Settings",
            },
        ),
    ]
